# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'direction_for_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(610, 423)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 20, 491, 371))
        self.label.setStyleSheet("font: 12pt \"楷体\";")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "1.点击\"导入excel\"按钮，依次将项目应收清单和收费标准选用导入，\n"
"这两个文件请从营账系统导出。\n"
"\n"
"2.左侧的数据列表框可供用户选中要查看的文件，右侧的文本框会显\n"
"示选中文件的数据内容。\n"
"\n"
"3.下方的输出选项是选择要保存的文件的地址，选择\"保存在原文件夹\n"
"内\"，则输出地址为项目应收清单所在的文件夹内，也可以点击浏览按\n"
"钮自主选择保存地址，只需填入文件名称，系统会自动增加\".xlsx\"的\n"
"文件后缀名。\n"
"\n"
"4.选好保存的地址后，点击物业费统计，如果选择保存在原文件夹内，\n"
"则会生成名为wyf的xlsx文件，点击维修基金统计，则会生成名为wxjj\n"
"的xlsx文件。\n"
"\n"
"5.生成物业费和维修基金计算清单后，不要关闭系统，直接点击费用\n"
"合并。选择默认地址生成名为fyhb的xlsx文件。\n"
"\n"
"6.费用合并清单，有一列异常列，判断物业费账期和日常维修账期是\n"
"否相同。"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
